name: bacteria_ia
channels:
  - conda-forge
  - nodefaults
dependencies:
  - matplotlib==3.8.4
  - numpy==1.26
  - pandas==2.2.2
  - python==3.11
  - pip==24.0
  - scipy==1.13.1
  - seaborn==0.13.2
  - scikit-learn==1.4.2
